### ISSUE TITLE
import library snort_listener

### ISSUE THREAD

**Issue by JockDaRock** [John-Lin/snort-socket#1]
I was using your library in Python3 which works mostly fine, but there was one problem I ran into.

while running my program with snortunsock I got an import error.  snort_listener was not able to import alert (from alert.py).  I was able to do this by going in making one modification.

```python
import alert
```
to

```python
import snortunsock.alert as alert
```

can you please change this and recommitt here and PyPi?

Kind Regards,
Jock

**Comment by John-Lin** [comment]
@JockDaRock Thanks for your testing on Python3. It was fixed and bumped to the next version on PyPi.

**Comment by JockDaRock** [comment]
awesome, thank you for such a fast response 🥇 ! Hope you have a great rest of your day @John-Lin
